name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5  # Ensure this version is correct and exists

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      - name: Create and push new branch
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          git checkout -b feature/terraform-deploy
          git add .
          git commit -m "Add Terraform configuration"
          git push origin feature/terraform-deploy

      - name: Create Pull Request
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Deploy Terraform changes"
          body: "This PR contains Terraform changes."
          base: main
          branch: feature/terraform-deploy

